K值确定：通过轮廓系数，越靠近1表示越好，-1表示越差

伪代码：


创建k个点作为初始的质心点（随机选择）

当任意一个点的簇分配结果发生改变时

       对数据集中的每一个数据点

              对每一个质心

                     计算质心与数据点的距离

              将数据点分配到距离最近的簇

       对每一个簇，计算簇中所有点的均值，并将均值作为质心

In [1]:
from numpy import *  
import time  
import matplotlib.pyplot as plt 

In [2]:
# 欧氏距离 
def euclDistance(vector1, vector2):  
    return sqrt(sum(power(vector2 - vector1, 2))) 

In [ ]:
# 初始化质心
def initCentroids(dataSet, k):  
    numSamples, dim = dataSet.shape  
    centroids = zeros((k, dim))  
    for i in range(k):  
        index = int(random.uniform(0, numSamples))  #随机选择一个数据点做质心
        centroids[i] = dataSet[index]  
    return centroids

In [ ]:
# k-means cluster  
def kmeans(dataSet, k):  
    numSamples = dataSet.shape[0]  
    # 第一列表示这个样本属于哪一个集群 
    # 第二列存储样本到该中心点的距离
    clusterAssment = mat(zeros((numSamples, 2)))  
    clusterChanged = True  
    
    ## step 1: 初始化质心 
    centroids = initCentroids(dataSet, k)
    
    while clusterChanged:  
        clusterChanged = False  
        ## for each sample  
        for i in xrange(numSamples):  
            minDist  = 100000.0  
            minIndex = 0  
            ## for each centroid  
            ## step 2: 找到最近的质点 
            for j in range(k):  
                distance = euclDistance(centroids[j, :], dataSet[i, :])  
                if distance < minDist:  
                    minDist  = distance  
                    minIndex = j  
              
            ## step 3: 更新簇  
            if clusterAssment[i, 0] != minIndex:  
                clusterChanged = True  
                clusterAssment[i, :] = minIndex, minDist**2  
  
        ## step 4: 更新中心点 
        for j in range(k):  
            pointsInCluster = dataSet[nonzero(clusterAssment[:, 0].A == j)[0]]  
            centroids[j, :] = mean(pointsInCluster, axis = 0)  
  
    print 'Congratulations, cluster complete!'  
    return centroids, clusterAssment  

In [3]:
zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [4]:
mat(zeros((5,2)))

matrix([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [9]:
  
centroids = zeros((3, 2))  
for i in range(3):  
    index = int(random.uniform(0, numSamples))  
    centroids[i, :] = dataSet[index, :]  


NameError: name 'numSamples' is not defined

In [7]:
zeros((5,2)).shape

(5, 2)

In [26]:
dataSet = [[1,2],[1,3],[2,3]]
dataSet= array(dataSet)

In [27]:
def initCentroids(dataSet, k):  
    numSamples, dim = dataSet.shape  
    centroids = zeros((k, dim))  
    for i in range(k):  
        index = int(random.uniform(0, numSamples))  #随机选择一个数据点做质心
        centroids[i] = dataSet[index]  
    return centroids

In [28]:
initCentroids(dataSet, 2)

array([[2., 3.],
       [1., 3.]])

In [21]:
k=2

In [22]:
numSamples, dim = dataSet.shape  
centroids = zeros((k, dim))  
for i in range(k):  
    index = int(random.uniform(0, numSamples))  #随机选择一个数据点做质心
    centroids[i, :] = dataSet[index, :] 

In [24]:
dataSet[1,:]

array([1, 3])

In [25]:
dataSet[1]

array([1, 3])